version: '2'
services:
    jhipsteruaa-app:
        image: jhipsteruaa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipsteruaa-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterUAA
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhipsteruaa-mongodb:
        extends:
            file: mongodb.yml
            service: jhipsteruaa-mongodb
